export default {
    en: {
      "homepage.title": "Hello, World!",
      "homepage.welcome": "Hi <strong>{{name}}</strong>, how are you?",
      "homepage.time": "The current time is: {{time}}",
      "menu.home": "Home",
      "menu.services": "Services",
      "menu.contact-us": "Contact us",
      "menu.login": "Login",
      "login.title.sub": "Enter your account to sign In or sign Up.",
      "login.form.button.login": "Sign in",
      "login.link.forgot-password": "Forgot Password?",
      "hero.title": "We provide simple, efficient and best solutions for all your IT problems!",
      "hero.sub-title": "Please \"Get Started\" to find out in more detail why our solutions are different from the others.",
      "hero.button-action": "Get Started!",
      "cta.button-action": "Contact Us on WA",
    },
    id: {
      "homepage.title": "¡Hola Mundo!",
      "homepage.welcome": "Hola, <strong>{{name}}</strong>, ¿cómo estás?",
      "homepage.time": "La hora actual es: {{time}}",
      "menu.home": "Beranda",
      "menu.services": "Layanan",
      "menu.contact-us": "Kontak",
      "menu.login": "Masuk",
      "login.title.sub": "Masukkan akun Anda untuk Masuk atau Mendaftar.",
      "login.form.button.login": "Masuk",
      "login.link.forgot-password": "Lupa Password?",
      "hero.title": "Kami menyediakan solusi yang sederhana dan efektif untuk segala masalah IT Anda!",
      "hero.sub-title": "Silahkan \"Mulai\" untuk mengetahui lebih detail mengapa solusi kami berbeda dari yang lainnya.",
      "hero.button-action": "Pelajari Lebih Lanjut",
      "cta.button-action": "Hubungi kami di WA",
    },
  };
  